### ISSUE TITLE
readHumidity

### ISSUE THREAD

**Issue by rickycraft** [enjoyneering/AHT10#1]
I think you ment to write .readHumidity instead fo reading again the temperature

https://github.com/enjoyneering/AHT10/blob/22614a8a88413f23602fe5efe341aaa4ac5d17ef/examples/AHT10_ESP8266_LCD_i2c/AHT10_ESP8266_LCD_i2c.ino#L122

**Comment by enjoyneering** [comment]
yes, thank you.

**Comment by enjoyneering** [comment]
done
