### ISSUE TITLE
Custom i2c pins for ESP32

### ISSUE THREAD

**Issue by jmw6773** [enjoyneering/AHT10#3]
Could the option of using non-standard i2c pins (21,22) be used for the ESP32 as well? 

https://github.com/enjoyneering/AHT10/blob/d046ea3c305e33e8d4986bf7a4d2227181d52fac/src/AHT10.h#L98-L99

Something like:
```
#if defined(ESP8266) || defined(ESP32)
 bool     begin(uint8_t sda = SDA, uint8_t scl = SCL);
```

**Comment by enjoyneering** [comment]
The 21, 22 are the I2C hardware pins. To use custom pins, you need a bit-bang I2C driver for the ESP32, which is not supported by this library.
