### ISSUE TITLE
Compile warnings ?

### ISSUE THREAD

**Issue by woeperbe** [enjoyneering/AHT10#5]
I use Microsoft visual studio and visual micro extension on NodeMcu boards
I have always compile warnings ?
![Annotation 2020-08-21 101423](https://user-images.githubusercontent.com/45015193/90868592-5131b380-e397-11ea-8157-6184374412aa.jpg)

**Comment by enjoyneering** [comment]
We have to ask Arduino ESP8266 support team why they use INTEGER if according to the I2C standard the device address is from 0 (general call) to 255 only. This is BYTE (UINT8_T).
